// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeloSyncOptimizer.Infrastructure.Persistence.Context;

#nullable disable

namespace VeloSyncOptimizer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429083614_UpdateGetUserByEmailSP")]
    partial class UpdateGetUserByEmailSP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.AlertSeverity", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AlertSeverities", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EntityName", "EntityId", "CreatedAt" }, "IX_AuditLogs_Entity")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "IX_AuditLogs_User")
                        .IsDescending(false, true);

                    b.ToTable("AuditLogs", "audit");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "Name" }, "UQ_Categories_Name")
                        .IsUnique();

                    b.ToTable("Categories", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.MovementType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_MovementTypes_Name")
                        .IsUnique();

                    b.ToTable("MovementTypes", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerishable")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTimeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ReorderQty")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SafetyStockDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Products_CategoryId")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex(new[] { "SKU" }, "IX_Products_SKU")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex(new[] { "SupplierId" }, "IX_Products_SupplierId")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex(new[] { "SKU" }, "UQ_Products_SKU")
                        .IsUnique();

                    b.ToTable("Products", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ExpectedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex(new[] { "StatusId", "CreatedAt" }, "IX_PO_StatusId")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SupplierId", "StatusId" }, "IX_PO_SupplierId");

                    b.HasIndex(new[] { "WarehouseId", "StatusId" }, "IX_PO_WarehouseId");

                    b.HasIndex(new[] { "PONumber" }, "UQ_PO_Number")
                        .IsUnique();

                    b.ToTable("PurchaseOrders", "procurement");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal?>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 4)")
                        .HasComputedColumnSql("([QuantityOrdered]*[UnitCost])", true);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id")
                        .HasName("PK_POLines");

                    b.HasIndex(new[] { "PurchaseOrderId" }, "IX_POLines_PO");

                    b.HasIndex(new[] { "ProductId" }, "IX_POLines_Product");

                    b.ToTable("PurchaseOrderLines", "procurement");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.PurchaseOrderStatus", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_POStatuses");

                    b.HasIndex(new[] { "Name" }, "UQ_POStatuses_Name")
                        .IsUnique();

                    b.ToTable("PurchaseOrderStatuses", "procurement");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.ReorderSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("ActionedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<decimal>("DaysOfStockLeft")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActioned")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal>("RollingAvgDaily")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<byte>("SeverityId")
                        .HasColumnType("tinyint");

                    b.Property<int>("SuggestedOrderQty")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex(new[] { "SeverityId", "IsActioned" }, "IX_Reorder_Severity");

                    b.HasIndex(new[] { "WarehouseId", "IsActioned", "GeneratedAt" }, "IX_Reorder_Warehouse")
                        .IsDescending(false, false, true);

                    b.ToTable("ReorderSuggestions", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.StockAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReadByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SeverityId")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReadByUserId");

                    b.HasIndex("SeverityId");

                    b.HasIndex(new[] { "ProductId", "CreatedAt" }, "IX_Alerts_Product")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "WarehouseId", "IsRead", "CreatedAt" }, "IX_Alerts_Warehouse")
                        .IsDescending(false, false, true);

                    b.ToTable("StockAlerts", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.StockLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnOrder")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("int");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_StockLevels_ProductId");

                    b.HasIndex(new[] { "WarehouseId", "ReorderPoint", "QuantityOnHand" }, "IX_StockLevels_Reorder");

                    b.HasIndex(new[] { "WarehouseId" }, "IX_StockLevels_WarehouseId");

                    b.HasIndex(new[] { "ProductId", "WarehouseId" }, "UQ_StockLevels_Prod_WH")
                        .IsUnique();

                    b.ToTable("StockLevels", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("MovementTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex(new[] { "ProductId", "WarehouseId", "CreatedAt" }, "IX_StockMov_Velocity");

                    b.HasIndex(new[] { "WarehouseId", "CreatedAt" }, "IX_StockMov_Warehouse_Date")
                        .IsDescending(false, true);

                    b.ToTable("StockMovements", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Suppliers_Name")
                        .IsUnique();

                    b.ToTable("Suppliers", "procurement");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.SupplierDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DaysLate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(case when [ActualDate] IS NOT NULL AND [ActualDate]>[PromisedDate] then datediff(day,[PromisedDate],[ActualDate]) else (0) end)", true);

                    b.Property<bool?>("IsOnTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("(case when [ActualDate] IS NOT NULL AND [ActualDate]<=[PromisedDate] then CONVERT([bit],(1)) else CONVERT([bit],(0)) end)", true);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("PromisedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PurchaseOrderId" }, "IX_Deliveries_PO");

                    b.HasIndex(new[] { "SupplierId", "PromisedDate" }, "IX_Deliveries_Supplier")
                        .IsDescending(false, true);

                    b.ToTable("SupplierDeliveries", "procurement");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.UserRole", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_UserRoles_Name")
                        .IsUnique();

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.VelocityCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("AvgDaily30")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal>("AvgDaily60")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal>("AvgDaily90")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<DateTime>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("PeakDailyQty")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "ComputedAt" }, "IX_Velocity_ComputedAt")
                        .IsDescending();

                    b.HasIndex(new[] { "ProductId", "WarehouseId" }, "UQ_VelocityCache_Prod_WH")
                        .IsUnique();

                    b.ToTable("VelocityCache", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex(new[] { "Code" }, "IX_Warehouses_Code")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex(new[] { "Code" }, "UQ_Warehouses_Code")
                        .IsUnique();

                    b.ToTable("Warehouses", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.WarehouseTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("DestMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransferNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id")
                        .HasName("PK_Transfers");

                    b.HasIndex("DestMovementId");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("SourceMovementId");

                    b.HasIndex(new[] { "DestWarehouseId" }, "IX_Transfers_Dest");

                    b.HasIndex(new[] { "ProductId", "CreatedAt" }, "IX_Transfers_Product")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SourceWarehouseId" }, "IX_Transfers_Source");

                    b.HasIndex(new[] { "TransferNumber" }, "UQ_Transfers_Number")
                        .IsUnique();

                    b.ToTable("WarehouseTransfers", "inventory");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Audit_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Category", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Categories_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Product", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Products_Category");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_Products_Supplier");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.User", "ApprovedByUser")
                        .WithMany("PurchaseOrderApprovedByUsers")
                        .HasForeignKey("ApprovedByUserId")
                        .HasConstraintName("FK_PO_ApprovedBy");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.User", "CreatedByUser")
                        .WithMany("PurchaseOrderCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_PO_CreatedBy");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.PurchaseOrderStatus", "Status")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_PO_Status");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_PO_Supplier");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_PO_Warehouse");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Status");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Product", "Product")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_POLines_Product");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_POLines_PO");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.ReorderSuggestion", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Product", "Product")
                        .WithMany("ReorderSuggestions")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Reorder_Product");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("ReorderSuggestions")
                        .HasForeignKey("PurchaseOrderId")
                        .HasConstraintName("FK_Reorder_PO");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.AlertSeverity", "Severity")
                        .WithMany("ReorderSuggestions")
                        .HasForeignKey("SeverityId")
                        .IsRequired()
                        .HasConstraintName("FK_Reorder_Severity");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("ReorderSuggestions")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Reorder_Warehouse");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Severity");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.StockAlert", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Product", "Product")
                        .WithMany("StockAlerts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Alerts_Product");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.User", "ReadByUser")
                        .WithMany("StockAlerts")
                        .HasForeignKey("ReadByUserId")
                        .HasConstraintName("FK_Alerts_ReadBy");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.AlertSeverity", "Severity")
                        .WithMany("StockAlerts")
                        .HasForeignKey("SeverityId")
                        .IsRequired()
                        .HasConstraintName("FK_Alerts_Severity");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("StockAlerts")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Alerts_Warehouse");

                    b.Navigation("Product");

                    b.Navigation("ReadByUser");

                    b.Navigation("Severity");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.StockLevel", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Product", "Product")
                        .WithMany("StockLevels")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockLevels_Product");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("StockLevels")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockLevels_Warehouse");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.User", "CreatedByUser")
                        .WithMany("StockMovements")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_StockMov_User");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.MovementType", "MovementType")
                        .WithMany("StockMovements")
                        .HasForeignKey("MovementTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMov_Type");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMov_Product");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("StockMovements")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMov_Warehouse");

                    b.Navigation("CreatedByUser");

                    b.Navigation("MovementType");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.SupplierDelivery", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("SupplierDeliveries")
                        .HasForeignKey("PurchaseOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Deliveries_PO");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Supplier", "Supplier")
                        .WithMany("SupplierDeliveries")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_Deliveries_Supplier");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.User", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.VelocityCache", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Product", "Product")
                        .WithMany("VelocityCaches")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Velocity_Product");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("VelocityCaches")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Velocity_Warehouse");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.User", "Manager")
                        .WithMany("Warehouses")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_Warehouses_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.WarehouseTransfer", b =>
                {
                    b.HasOne("VeloSyncOptimizer.Domain.Entities.StockMovement", "DestMovement")
                        .WithMany("WarehouseTransferDestMovements")
                        .HasForeignKey("DestMovementId")
                        .HasConstraintName("FK_Transfers_DstMovement");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "DestWarehouse")
                        .WithMany("WarehouseTransferDestWarehouses")
                        .HasForeignKey("DestWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Transfers_Dest");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.User", "InitiatedByUser")
                        .WithMany("WarehouseTransfers")
                        .HasForeignKey("InitiatedByUserId")
                        .HasConstraintName("FK_Transfers_User");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Product", "Product")
                        .WithMany("WarehouseTransfers")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Transfers_Product");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.StockMovement", "SourceMovement")
                        .WithMany("WarehouseTransferSourceMovements")
                        .HasForeignKey("SourceMovementId")
                        .HasConstraintName("FK_Transfers_SrcMovement");

                    b.HasOne("VeloSyncOptimizer.Domain.Entities.Warehouse", "SourceWarehouse")
                        .WithMany("WarehouseTransferSourceWarehouses")
                        .HasForeignKey("SourceWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Transfers_Source");

                    b.Navigation("DestMovement");

                    b.Navigation("DestWarehouse");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("Product");

                    b.Navigation("SourceMovement");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.AlertSeverity", b =>
                {
                    b.Navigation("ReorderSuggestions");

                    b.Navigation("StockAlerts");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.MovementType", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Product", b =>
                {
                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("ReorderSuggestions");

                    b.Navigation("StockAlerts");

                    b.Navigation("StockLevels");

                    b.Navigation("StockMovements");

                    b.Navigation("VelocityCaches");

                    b.Navigation("WarehouseTransfers");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("ReorderSuggestions");

                    b.Navigation("SupplierDeliveries");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.PurchaseOrderStatus", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.StockMovement", b =>
                {
                    b.Navigation("WarehouseTransferDestMovements");

                    b.Navigation("WarehouseTransferSourceMovements");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SupplierDeliveries");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PurchaseOrderApprovedByUsers");

                    b.Navigation("PurchaseOrderCreatedByUsers");

                    b.Navigation("StockAlerts");

                    b.Navigation("StockMovements");

                    b.Navigation("WarehouseTransfers");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VeloSyncOptimizer.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("ReorderSuggestions");

                    b.Navigation("StockAlerts");

                    b.Navigation("StockLevels");

                    b.Navigation("StockMovements");

                    b.Navigation("VelocityCaches");

                    b.Navigation("WarehouseTransferDestWarehouses");

                    b.Navigation("WarehouseTransferSourceWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
